### ISSUE TITLE
Allow customizing explanatory comment

### ISSUE THREAD

**Issue by raxod502** [twbs/no-carrier#22]
I'd like to use some different text for the explanatory comment that is posted when an issue is closed. However, currently the only way to do that is to fork the repository and build from source. It would be much more convenient to allow exporting an optional environment variable to override the explanatory comment.

**Comment by cvrebert** [comment]
Yeah, I'm in favor of it being customizable. Problem is, that implies picking a templating system, and I've no idea which to choose. Recommendations welcomed.

**Comment by raxod502** [comment]
For something as simple as this, I don't think it would be remiss to just use `$DAYS_ELAPSED`, `$LABEL_NAME`, etc. and then allow `\$LABEL_NAME` for quoting. I don't do Scala but it [looks like](https://stackoverflow.com/q/5675820/3538165) you can do regex replacement using a function of the match, so this would be pretty trivial implementation-wise.

I'm sure there are more elegant solutions though.

**Comment by raxod502** [comment]
I wrote a replacement in Python that has this feature: https://github.com/raxod502/tidier.
