### ISSUE TITLE
Does it close pull requests as well?

### ISSUE THREAD

**Issue by raxod502** [twbs/no-carrier#24]
I know that GitHub treats issues and pull requests as part of the same internal system, so it doesn't seem implausible to me that NO CARRIER automatically closes both, even though it only explicitly mentions issues.

If this is true, then I would recommend mentioning it in the documentation (I could provide a pull request for this); otherwise, I guess this is a feature request—auto-closing pull requests is also very useful.

**Comment by cvrebert** [comment]
Yes, it works on pull requests too, for the reason you mentioned.
Example: https://github.com/twbs/bootstrap/pull/20151#issuecomment-230694148
